/**
 * エクスポート & 共有マネージャー (Exporter)
 * 階層化データ（レーン > 選手）をプレーンテキスト(.txt) / CSV(.csv)形式に整形し、
 * iOS共有シート(Web Share API / AirDrop / メール / メモ帳)やファイル保存を実行します。
 */

import { TimerEngine } from './timer-engine.js';

export class Exporter {
  /**
   * プレーンテキスト形式の生成（レーン別・選手別）
   */
  static generateTextFormat(session) {
    const lines = [];
    lines.push('========================================');
    lines.push(`🏊 AQUATIMER PRO - 水泳計測記録`);
    lines.push('========================================');
    lines.push(`タイトル: ${session.title || '計測セッション'}`);
    lines.push(`計測日時: ${session.displayDate || new Date(session.createdAt).toLocaleString('ja-JP')}`);
    lines.push(`総経過時間: ${TimerEngine.formatTime(session.totalElapsed, true)}`);
    lines.push(`登録数: ${session.lanes.length} レーン / 合計 ${session.totalSwimmers || session.lanes.reduce((acc, l) => acc + (l.swimmers ? l.swimmers.length : 1), 0)} 名`);
    lines.push('----------------------------------------\n');

    session.lanes.forEach(lane => {
      lines.push(`■【${lane.name}】(レーン ${lane.laneNumber})`);
      lines.push('----------------------------------------');

      const swimmers = lane.swimmers || [];
      if (swimmers.length === 0) {
        lines.push('  (登録選手なし)\n');
        return;
      }

      swimmers.forEach(swimmer => {
        const offsetStr = swimmer.offsetSeconds > 0 ? ` (時間差: +${swimmer.offsetSeconds}s)` : ' (同時スタート)';
        lines.push(`  ● 選手: ${swimmer.name} [泳順: #${swimmer.order}]${offsetStr}`);
        lines.push(`    最終タイム: ${TimerEngine.formatTime(swimmer.finalTime)}`);
        
        if (swimmer.bestLap !== null) {
          lines.push(`    最速ラップ: ${TimerEngine.formatTime(swimmer.bestLap)} | 平均ラップ: ${TimerEngine.formatTime(swimmer.avgLap)}`);
        }

        if (swimmer.laps && swimmer.laps.length > 0) {
          lines.push('    No. | 区間タイム (Lap) | 累積タイム (Split)');
          swimmer.laps.forEach(l => {
            const numStr = String(l.lapNumber).padStart(3, ' ');
            const lapStr = TimerEngine.formatTime(l.lapTime).padStart(8, ' ');
            const splitStr = TimerEngine.formatTime(l.splitTime).padStart(8, ' ');
            lines.push(`    #${numStr} | ${lapStr} | ${splitStr}`);
          });
        } else {
          lines.push('    (ラップ記録なし)');
        }
        lines.push('');
      });
      lines.push('');
    });

    lines.push('========================================');
    lines.push('Generated by AquaTimer Pro');
    return lines.join('\n');
  }

  /**
   * CSV形式の生成 (Excel対応 UTF-8 BOM付き)
   */
  static generateCsvFormat(session) {
    const rows = [];
    rows.push([
      'レーン番号', 
      'レーン名', 
      '泳順', 
      '選手名', 
      '時間差(秒)', 
      'Lap番号', 
      '区間タイム(Lap)', 
      '累積タイム(Split)', 
      '区間ミリ秒', 
      '累積ミリ秒'
    ]);

    session.lanes.forEach(lane => {
      const swimmers = lane.swimmers || [];
      swimmers.forEach(swimmer => {
        if (swimmer.laps && swimmer.laps.length > 0) {
          swimmer.laps.forEach(l => {
            rows.push([
              lane.laneNumber,
              `"${lane.name.replace(/"/g, '""')}"`,
              swimmer.order,
              `"${swimmer.name.replace(/"/g, '""')}"`,
              swimmer.offsetSeconds,
              l.lapNumber,
              TimerEngine.formatTime(l.lapTime),
              TimerEngine.formatTime(l.splitTime),
              l.lapTime,
              l.splitTime
            ]);
          });
        } else {
          rows.push([
            lane.laneNumber,
            `"${lane.name.replace(/"/g, '""')}"`,
            swimmer.order,
            `"${swimmer.name.replace(/"/g, '""')}"`,
            swimmer.offsetSeconds,
            '-',
            '-',
            TimerEngine.formatTime(swimmer.finalTime),
            0,
            swimmer.finalTime
          ]);
        }
      });
    });

    const csvContent = rows.map(e => e.join(',')).join('\r\n');
    return '\uFEFF' + csvContent;
  }

  /**
   * iOS共有シート / Web Share API によるエクスポート
   */
  static async shareSession(session, format = 'text') {
    const isCsv = format === 'csv';
    const content = isCsv ? this.generateCsvFormat(session) : this.generateTextFormat(session);
    const mimeType = isCsv ? 'text/csv;charset=utf-8' : 'text/plain;charset=utf-8';
    const ext = isCsv ? 'csv' : 'txt';
    const cleanTitle = (session.title || 'aquatimer_record').replace(/[\/\\:*?"<>|]/g, '_');
    const filename = `${cleanTitle}_${Date.now()}.${ext}`;

    const blob = new Blob([content], { type: mimeType });
    const file = new File([blob], filename, { type: mimeType });

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          files: [file],
          title: session.title || '水泳計測記録',
          text: `AquaTimer Pro 計測記録: ${session.title}`
        });
        return { success: true, method: 'native_share' };
      } catch (err) {
        if (err.name === 'AbortError') {
          return { success: false, aborted: true };
        }
      }
    }

    if (navigator.share) {
      try {
        await navigator.share({
          title: session.title || '水泳計測記録',
          text: content
        });
        return { success: true, method: 'text_share' };
      } catch (err) {
        if (err.name === 'AbortError') {
          return { success: false, aborted: true };
        }
      }
    }

    this.downloadFile(blob, filename);
    return { success: true, method: 'download' };
  }

  /**
   * ファイルダウンロード
   */
  static downloadFile(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 200);
  }

  /**
   * クリップボードコピー
   */
  static async copyToClipboard(session, format = 'text') {
    const content = format === 'csv' 
      ? this.generateCsvFormat(session) 
      : this.generateTextFormat(session);

    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(content);
      return true;
    } else {
      const textarea = document.createElement('textarea');
      textarea.value = content;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    }
  }
}
